input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [service] {
    mutate {
      add_field => { "[@metadata][index]" => "school-logs-%{service}" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][index]" => "school-logs-unknown" }
    }
  }

  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
    remove_field => ["timestamp"]
  }

  mutate {
    remove_field => ["port", "host", "@version"]
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
  }
}
